pypi:
    image:
        name: pretix/ci-image
    script:
        - cat $PYPIRC > ~/.pypirc
        - pip install -U pip uv
        - uv pip install --system -U setuptools wheel twine build
        - python -m build
        - twine check dist/*
        - twine upload dist/*
    only:
        - '/^v[0-9].*$/'
    artifacts:
        paths:
            - dist/
