[tox]
envlist =
    django{42,50,51,52}-{sqlite,postgres,mariadb}
    style

[testenv]
passenv = TOXDB,TOXENV,CI,TRAVIS,TRAVIS_*
deps =
    -e .[dev]
    django42: Django==4.2.*
    django50: Django==5.0.*
    django51: Django==5.1.*
    django52: Django==5.2.*
setenv =
    sqlite: TOXDB=sqlite
    postgres: TOXDB=postgres
    mariadb: TOXDB=mariadb
commands = pytest tests --stepwise -vv

[testenv:style]
basepython=python3.14
deps=
    -e .[dev]
    django==5.2.*
setenv =
    TOXDB=sqlite
commands =
    ruff check django-ormql tests
    ruff format --check django-ormql tests
