[tox]
envlist =
    django{42,52,60}-{sqlite,postgres}
    style

[testenv]
passenv = TOXDB,TOXENV,CI,TRAVIS,TRAVIS_*
deps =
    -e .[dev]
    django42: Django==4.2.*
    django52: Django==5.2.*
    django60: Django==6.0.*
    postgres: psycopg2-binary
setenv =
    sqlite: TOXDB=sqlite
    postgres: TOXDB=postgres
commands = pytest tests --stepwise -vv

[testenv:style]
basepython=python3.14
deps=
    -e .[dev]
    django==5.2.*
setenv =
    TOXDB=sqlite
commands =
    ruff check django_ormql tests
    ruff format --check django_ormql tests
    check-manifest .
